-- Create the wishes table for RSVPs and messages
CREATE TABLE IF NOT EXISTS wishes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  name TEXT NOT NULL,
  attendance TEXT NOT NULL CHECK (attendance IN ('Attending', 'Not Attending')),
  guests INTEGER NOT NULL DEFAULT 1,
  message TEXT NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE wishes ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow anyone to read wishes (Public Read)
CREATE POLICY "Allow public read access" ON wishes
  FOR SELECT USING (true);

-- Create a policy to allow anyone to insert a wish (Public Insert)
CREATE POLICY "Allow public insert access" ON wishes
  FOR INSERT WITH CHECK (true);

-- Indices for performance
CREATE INDEX IF NOT EXISTS wishes_created_at_idx ON wishes (created_at DESC);
