export const config = {
    coupleNames: process.env.NEXT_PUBLIC_COUPLE_NAMES || "Dawit & Bethlehem",
    eventDate: process.env.NEXT_PUBLIC_EVENT_DATE || "2026-01-11T10:00:00",
    groom: process.env.NEXT_PUBLIC_GROOM_NAME || "Dawit Tesfaye",
    groomNickName: process.env.NEXT_PUBLIC_GROOM_NICKNAME || "Dawit",
    groomInstagram: process.env.NEXT_PUBLIC_GROOM_INSTAGRAM || "dawittesfaye",
    groomBio: process.env.NEXT_PUBLIC_GROOM_BIO || "A kind-hearted man of faith whose calm spirit, loyalty, and humor make every season of life brighter.",
    bride: process.env.NEXT_PUBLIC_BRIDE_NAME || "Bethlehem Alemu",
    brideNickName: process.env.NEXT_PUBLIC_BRIDE_NICKNAME || "Bethlehem",
    brideInstagram: process.env.NEXT_PUBLIC_BRIDE_INSTAGRAM || "bethlehemalemu",
    brideBio: process.env.NEXT_PUBLIC_BRIDE_BIO || "Graceful, joyful, and deeply thoughtful, she brings warmth, beauty, and peace wherever she goes.",
    bibleVerse: process.env.NEXT_PUBLIC_BIBLE_VERSE || "Ecclesiastes 4:9",
    bibleVerseContent: process.env.NEXT_PUBLIC_BIBLE_VERSE_CONTENT || "Two are better than one, because they have a good reward for their labor.",
    timeline_1: process.env.NEXT_PUBLIC_YEAR_1 || "First Meeting",
    timeline_1_content: process.env.NEXT_PUBLIC_YEAR_1_CONTENT || "What began as a simple introduction soon grew into a friendship marked by prayer, laughter, and genuine care.",
    timeline_2: process.env.NEXT_PUBLIC_YEAR_2 || "Growing Together",
    timeline_2_content: process.env.NEXT_PUBLIC_YEAR_2_CONTENT || "As the seasons passed, our bond deepened through family, faith, and shared dreams for the future.",
    timeline_3: process.env.NEXT_PUBLIC_YEAR_3 || "The Promise",
    timeline_3_content: process.env.NEXT_PUBLIC_YEAR_3_CONTENT || "With grateful hearts, we said yes to forever and now invite you to celebrate this beautiful beginning with us.",
    holyMatrimony: {
        enabled: process.env.NEXT_PUBLIC_HOLY_MATRIMONY === 'true',
        time: process.env.NEXT_PUBLIC_HOLY_MATRIMONY_TIME || "10:00 AM",
        place: process.env.NEXT_PUBLIC_HOLY_MATRIMONY_PLACE || "St. Gabriel Church",
        place_details: process.env.NEXT_PUBLIC_HOLY_MATRIMONY_PLACE_DETAILS || "Addis Ababa, Ethiopia",
        googleMapsLink: process.env.NEXT_PUBLIC_HOLY_MATRIMONY_GOOGLE_MAPS || "https://maps.app.goo.gl/vPmfWux29qYYfkJTA",
    },
    weddingReception: {
        enabled: process.env.NEXT_PUBLIC_WEDDING_RECEPTION === 'true',
        time: process.env.NEXT_PUBLIC_WEDDING_RECEPTION_TIME || "1:00 PM",
        place: process.env.NEXT_PUBLIC_WEDDING_RECEPTION_PLACE || "Skylight Hotel",
        place_details: process.env.NEXT_PUBLIC_WEDDING_RECEPTION_PLACE_DETAILS || "Bole, Addis Ababa, Ethiopia",
        googleMapsLink: process.env.NEXT_PUBLIC_WEDDING_RECEPTION_GOOGLE_MAPS || "https://maps.app.goo.gl/fQGiC37iEx6fcuNq8",
    },
    livestreaming: {
        enabled: process.env.NEXT_PUBLIC_LIVE_STREAMING === 'true',
        time: process.env.NEXT_PUBLIC_LIVE_STREAMING_TIME || "10:00 AM",
        link: process.env.NEXT_PUBLIC_LIVE_STREAMING_LINK || "#",
        detail: process.env.NEXT_PUBLIC_LIVE_STREAMING_DETAIL || "Join us online and celebrate this special day with our families from wherever you are.",
    },
    prewedding: {
        enabled: process.env.NEXT_PUBLIC_PREWEDDING === 'true',
        link: process.env.NEXT_PUBLIC_PREWEDDING_CODE_LINK_EMBED || "#",
        detail: process.env.NEXT_PUBLIC_PREWEDDING_DETAIL || "A glimpse into our journey, our joy, and the love that brought us here.",
    },
    rsvp: {
        enabled: process.env.NEXT_PUBLIC_RSVP === 'true',
        detail: process.env.NEXT_PUBLIC_RSVP_DETAIL || "Please confirm your attendance and leave your warm wishes for the couple.",
    },
    thankyou: process.env.NEXT_PUBLIC_THANKYOU || "Thank You",
    thankyouDetail: process.env.NEXT_PUBLIC_THANKYOU_DETAIL || "Thank you for your love, your prayers, and for being part of this unforgettable celebration.",
};
